---
title: "corti model"
author: "Jurrien"
date: "28-4-2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
parameters <- c(ks_Rm = 2.90, IC50_Rm = 26.2, kon = 0.00329, kT = 0.63, kre = 0.57, Rf = 0.49, kd_R = 0.0572,
                kd_Rm = 0.612, ks_r = 3.22, D = 53, Rm0 = 4.74, DR = 0, DRN = 0)

Glucocorticoid_func <- function(t, y, parms) {
    with(as.list(c(y, parms)),{
      
      # Dit model bevat 4 afgeleide functies:
      # Afgeleide 1:
  
      dmRNAr_dt <- ks_Rm * ( 1 - (DRN / (IC50_Rm + DRN))) - kd_Rm * mRNAr
  
      # Afgeleide 2:
  
      dR_dt <- ks_r * mRNAr + Rf * kre * DRN - kon * D * R - kd_R * R
      
      # Afgeleide 3:
  
      dDR_dt <- kon * D * R - kT * DR
  
      # Afgeleide 4:
  
      dDRN_dt <- kT * DR - kre * DRN
      
      return(list(c(dmRNAr_dt, dR_dt, dDR_dt, dDRN_dt)))
       }
       )
}

state <- c(mRNAr = 4.74, R = 267, DR = 0, DRN = 0)
t <- seq(0, 48, by = 1)

out <- deSolve::ode(times = t, y = state, parms = parameters, func = Glucocorticoid_func, method = "euler")
plot(out)
```

